#!/bin/bash

# The MIT License (MIT)

# Copyright (c) 2015 Philipp Heckel

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WAIT=60

usage() {
        echo "Usage: zfsres <pool> <slow-mirror>"
        echo "Enable slow mirror(s) and wait for them to be resilvered and exit."
        echo ""
        echo "Arguments:"
        echo "  <pool>           - Name of the ZFS pool, e.g. tank"
        echo "  <slow-mirror>    - Description of a slow mirror device, e.g. wwn-0x50004cf20c41a05b"
        echo ""
}

pool=$1
slowmirror=$2

# Check mandatory options
[ -z "$pool" -o -z "$slowmirror" ] && { usage; exit 1; }

# Must run as root
if [ "$(id -u)" != "0" ]; then
        echo "Script must be run as root."
        exit 1
fi

if [ -n "$(zpool status $pool | grep $slowmirror | grep ONLINE)" ]; then
        echo "[$(date)] Slow mirror already online. Resilvering canceled."
        exit 2
fi

echo -n "[$(date)] Activating slow mirror $slowmirror on pool $pool ..."
zpool online $pool $slowmirror
echo " OK"

echo -n "[$(date)] Waiting $WAIT seconds for resilvering to start ..."
sleep $WAIT
echo " OK"

echo -n "[$(date)] Waiting for resilvering to finish ..."
while [ -n "$(zpool status $pool | grep resilvering)" ]; do
        echo -n "."
        sleep 3
done
echo " OK"

echo -n "[$(date)] Deactivating slow mirror $slowmirror on pool $pool ..."
zpool offline $pool $slowmirror
echo " OK"

